### ISSUE TITLE
Server startet nicht mehr

### ISSUE THREAD

**Issue by rrrene** [atlas-engine/AtlasEngine.FullstackServer#9]
Ich wollte meine AE, mit der ich [dieses Issue](https://github.com/atlas-engine/ProcessEngine.CompatibilityProxyAdapter/issues/6) produziert habe, wieder starten und sie bricht leider beim Laden ab:

```shell
$ npm start

> @atlas-engine/fullstack_server@0.1.0 start /Users/rrrene/projects/atlas-engine/AtlasEngine.FullstackServer
> node ./bin/index.js

2020-03-11T08:14:09.265Z - info: [atlasengine:fullstack_server:application] Starting up server application, version 0.1.0...
2020-03-11T08:14:09.266Z - info: [atlasengine:fullstack_server:application] Using HTTP endpoint http://0.0.0.0:8000
2020-03-11T08:14:09.267Z - info: [atlasengine:fullstack_server:application] Using websocket endpoint http://0.0.0.0:8000
2020-03-11T08:14:09.267Z - info: [atlasengine:fullstack_server:application] Running migrations...
2020-03-11T08:14:09.354Z - info: [atlasengine:sequelize_connection_manager] Connection to sqlite database '/Users/rrrene/Library/Application Support/AtlasEngineFullstackServer/databases/atlasengine.sqlite' established.
2020-03-11T08:14:09.409Z - info: [atlasengine:sequelize_connection_manager] Disposing connection to sqlite database '/Users/rrrene/Library/Application Support/AtlasEngineFullstackServer/databases/atlasengine.sqlite'...
2020-03-11T08:14:09.410Z - info: [atlasengine:sequelize_connection_manager] Done.
2020-03-11T08:14:10.244Z - error: [atlasengine:iam:iam_service] allowDummyToken is set to true. This allows unauthorized access with no restrictions. Never use this setting in a production environment!
2020-03-11T08:14:10.259Z - verbose: [atlasengine:persistence:cronjob_history_repository] Initializing Sequelize connection and loading models...
2020-03-11T08:14:10.260Z - info: [atlasengine:sequelize_connection_manager] Connection to sqlite database '/Users/rrrene/Library/Application Support/AtlasEngineFullstackServer/databases/atlasengine.sqlite' established.
2020-03-11T08:14:10.272Z - verbose: [atlasengine:persistence:cronjob_history_repository] Done.
2020-03-11T08:14:10.274Z - verbose: [atlasengine:persistence:process_definition_repository] Initializing Sequelize connection and loading models...
2020-03-11T08:14:10.274Z - info: [atlasengine:sequelize_connection_manager] Active connection to sqlite database '/Users/rrrene/Library/Application Support/AtlasEngineFullstackServer/databases/atlasengine.sqlite' found.
2020-03-11T08:14:10.290Z - verbose: [atlasengine:persistence:process_definition_repository] Done.
2020-03-11T08:14:10.291Z - verbose: [atlasengine:persistence:process_instance_repository] Initializing Sequelize connection and loading models...
2020-03-11T08:14:10.291Z - info: [atlasengine:sequelize_connection_manager] Active connection to sqlite database '/Users/rrrene/Library/Application Support/AtlasEngineFullstackServer/databases/atlasengine.sqlite' found.
2020-03-11T08:14:10.306Z - verbose: [atlasengine:persistence:process_instance_repository] Done.
2020-03-11T08:14:10.306Z - verbose: [atlasengine:persistence:external_task_repository] Initializing Sequelize connection and loading models...
2020-03-11T08:14:10.306Z - info: [atlasengine:sequelize_connection_manager] Active connection to sqlite database '/Users/rrrene/Library/Application Support/AtlasEngineFullstackServer/databases/atlasengine.sqlite' found.
2020-03-11T08:14:10.326Z - verbose: [atlasengine:persistence:external_task_repository] Done.
2020-03-11T08:14:10.326Z - verbose: [atlasengine:persistence:flow_node_instance_repository] Initializing Sequelize connection and loading models...
2020-03-11T08:14:10.326Z - info: [atlasengine:sequelize_connection_manager] Active connection to sqlite database '/Users/rrrene/Library/Application Support/AtlasEngineFullstackServer/databases/atlasengine.sqlite' found.
2020-03-11T08:14:10.357Z - verbose: [atlasengine:persistence:flow_node_instance_repository] Done.
2020-03-11T08:14:10.483Z - info: [atlasengine:fullstack_server:application] Bootstrapper started successfully.
2020-03-11T08:14:10.484Z - info: [atlasengine:fullstack_server:application] Starting Services...
2020-03-11T08:14:10.486Z - info: [atlasengine:runtime:auto_start_service] Starting up and creating subscriptions...
2020-03-11T08:14:10.486Z - info: [atlasengine:runtime:auto_start_service] Done.
2020-03-11T08:14:10.486Z - info: [atlasengine:fullstack_server:application] AutoStartService started.
2020-03-11T08:14:10.486Z - info: [atlasengine:runtime:cronjob_service] Starting up and creating Cronjobs...
2020-03-11T08:14:10.523Z - error: [atlasengine:fullstack_server:application] Failed to start the internal services. TypeError: this.processes.flatMap is not a function
    at Definitions.getAllStartEvents (/Users/rrrene/projects/atlas-engine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/process_model/dist/commonjs/definitions.js:18:44)
    at CronjobService.getActiveCyclicTimerStartEventsForProcessDefinition (/Users/rrrene/projects/atlas-engine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/core_domain.process_model_execution/dist/commonjs/cronjob_service.js:191:58)
    at processDefinitions.filter (/Users/rrrene/projects/atlas-engine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/core_domain.process_model_execution/dist/commonjs/cronjob_service.js:157:49)
    at Array.filter (<anonymous>)
    at CronjobService.getProcessesWithCronjobs (/Users/rrrene/projects/atlas-engine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/core_domain.process_model_execution/dist/commonjs/cronjob_service.js:156:67)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @atlas-engine/fullstack_server@0.1.0 start: `node ./bin/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @atlas-engine/fullstack_server@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rrrene/.npm/_logs/2020-03-11T08_14_10_546Z-debug.log
```

**Comment by ElRaptorus** [comment]
Mein inneres Herz blutet grade... `flatMap is not a function` 😢 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

Scheinbar gibts das erst seit Node v11.
 
Ich hatte gehofft, dass wir das benutzen können, weil flatMap schon echt sexy ist. Aber wird wohl nix draus. 😭 

Werd ich fixen.

**Comment by ElRaptorus** [comment]
@rrrene Ich habe eben einen Fix für das Paket gepublished. Versuch mal die Anwendung neu zu installieren und zu starten. Das sollte jetzt wieder funktionieren.

**Comment by rrrene** [comment]
Läuft 👍
